### ISSUE TITLE
Safari not rendering translator

### ISSUE THREAD

**Issue by darryn** [kriskowal/tengwarjs#1]
Hi @kriskowal,

Just been checking out your translator and noticed that it doesn't seem to work on Safari. Apparantly there is an error (Can't observe non-configurable properties) on line 5254 of 'index.html.bundle-0.js':

<pre>null !== c ? (Wo = t, n = zo(n, i, u, c), null === n ? (Uo = t, t = n) : t = n) : (Uo = t, t = et)</pre>

This is a little beyond my skills to fix so I just thought I would let you know.

Cheers,

**Comment by kriskowal** [comment]
I have done a release at some point this year. I am hoping this issue is resolved. Please reopen if it’s found to still be broken in Safari. It seems to work for me.
