### ISSUE TITLE
plain = true still includes HTML entities

### ISSUE THREAD

**Issue by galadhremmin** [kriskowal/tengwarjs#10]
By setting `plain` to `true`, the transcriber still generate HTML entities, which won't render the correct transcription if the result is put in a text field. 

    import { transcribe as transcribeGeneralUse, makeOptions as makeOptionsForGeneralUse } from 'tengwar/general-use';
    import TengwarParmaite from 'tengwar/tengwar-parmaite';

    let options = makeOptionsForGeneralUse();

    options.font = TengwarParmaite;
    options.plain = true;
    options.block = false;

    const transcription = transcribeGeneralUse('edhellen', options);
    console.log(transcription); // --> "4$jR&#176;5$"  (&#176; should be °)

The only way I know how to "fix" this at the moment is to manually parse HTML entities using regular expressions:

    transcription = transcription.replace(/&(#(?:x[0-9a-f]+|\d+)|[a-z]+);?/gi, function($0, $1) {
        if ($1[0] === "#") {
            return String.fromCharCode($1[1].toLowerCase() === "x" 
                ? parseInt($1.substr(2), 16)  
                : parseInt($1.substr(1), 10));
        }

        return $0;
    });

Also, thank you for making this awesome library! 🥇

**Comment by kriskowal** [comment]
It would perhaps be better to go the other way and simply use UTF-8 at the core, translate to HTML entities if necessary.

I’m about to spend some time in Iceland and Spain. A PR would be most welcome. From there I intend to liberally grant collaborator rights (to push branches and land your own PR’s), and npm publish rights.

**Comment by kriskowal** [comment]
Published fix in 1.2.4.
