### ISSUE TITLE
Miscellaneous improvements to mode for general use

### ISSUE THREAD

**Issue by kriskowal** [kriskowal/tengwarjs#15]
From Fiona Jallings,
```
PH > Q

Consonant Y > h

J > s

IE > lG

OE > lH

But others are leaving them perplexed on how to fix them:

 

Vowel Y > `Û

And

 

Double vowels:

Lee > j`V`V

Feet > e`V1F

Loo > j`N`N

Foot > e`N1H

Aaron > `C7D5^

Continuum > z1[H5%`Mt&

(ii is super rare, but I think you get the pattern by now.)
```

**Comment by dreamingfifi** [comment]
So here is what these would look like when done correctly:
![tengwar-corrections](https://user-images.githubusercontent.com/56487771/66706879-db2fdb00-ecf5-11e9-9214-f7d844ebbaf1.png)

**Comment by kriskowal** [comment]
Opened tickets for individual cases #51, #55 and coverage for cases already passing #56.
