### ISSUE TITLE
Tengwar shorthand notation

### ISSUE THREAD

**Issue by kriskowal** [kriskowal/tengwarjs#25]
It may be useful for tests to use a shorthand of my Tengwar Object Notation. The current form is very explicit but very verbose. I am thinking of a form that might look like:

```
thule;silme-nuquerna:e;short-carrier:e
Th SnE ScE
```

```
helcaraxë
hyarmen;lambe:e;quesse;romen:a;quesse:a,s;short-carrier:e output
Hy EL Q AR AQS ScE
```

**Comment by dreamingfifi** [comment]
Is there a full list of all of the symbols and the names you've given them somewhere? That way I could show the proper use of the vowel Y.

**Comment by kriskowal** [comment]
All of the names are in `alphabet.js`. I’m open to renaming the file `abugida.js` in the interest of strict correctness.
