### ISSUE TITLE
Need Dan Smith key bindings for vowel Y.

### ISSUE THREAD

**Issue by kriskowal** [kriskowal/tengwarjs#28]
The file `dan-smith.js` has a note for the "y" bindings, which are rendered as a diaeresis below the tengwa. The inverted hat is missing. We can tentatively call this "y-above" and need the four codes designated for Dan Smith fonts.

Dan’s documentation has gotten scarce from the Internet since the Tolkien Estate requested it be taken down. We would need those four characters to start.

The next step after that would be to go into tengwar-parmaite.js and tengwar-annatar.js and note the corresponding index for rendering above each tengwa. The format for these tables is that each tengwa has a typical position, noted as "others". So if "tinco.others" is 2, that means that the second glyph from dan-smith.js will be used to position every vowel over the metal tengwa. There are then overrides for each special case where the tehta didn’t fit over the tengwa correctly in each font. You can see the results at the end of the proofs page that the command `npm build` generates at `public/index.html` or in the staging deployment that gets created with every pull request.

Once these steps have been taken, it’s possible to use "y-above" in the transcribers instead of "y" in some places like the mode for general use. In all cases where y-above is default, it should be possible to override the behavior with a following slash `/` to produce y-below.

In a follow-up change, I would like to rename y to y-below and y-above to merely y to remain consistent with the other vowel naming conventions.

**Comment by dreamingfifi** [comment]
There are 3 y-tehtar. There's the consonant Y which goes under and is double-dots, the Sindarin vowel Y which is double dots and goes over, and the English little v-shaped vowel Y that goes over.

The English vowel Y is in the font as these four characters:
On a wide tengwa: Ø
On a regular tengwa: Ù
On a regular tengwa with the telco rising on the left: Ú
On a vowel carrier:  Û

**Comment by dreamingfifi** [comment]
![vowel-y-sample](https://user-images.githubusercontent.com/56487771/66719870-71293b80-edb2-11e9-9872-f2615137297a.png)
