### ISSUE TITLE
Rename the S hooks

### ISSUE THREAD

**Issue by kriskowal** [kriskowal/tengwarjs#29]
Per, http://at.mansbjorkman.net/teng_names.htm, the S hook is called "sa-rince". There are, however, four S hooks including a looped hook that’s intended to pronounce a final Z.

* "s-final" is "sa-rince"
* "s-inverted" is a bent upward and may not have an attested name.
* "s-extended" is bent downward and may also be nameless.
* "s-flourish" is the Z variant. I would be tempted to call it "za-rince" if there is no attested name.

**Comment by dreamingfifi** [comment]
Sure, I call it sa-rince myself, but being able to remember the names of the symbols is also really handy, which is why I like the "s-" version you already have.

**Comment by kriskowal** [comment]
Since sa-rinci is a class of symbols and doesn’t apply especially well to any of these in particular, we’re confined to use these or name them like sa-rince, sa-rince-up, sa-rince-down, and za-rince, which might be more or less clear. Going to table this for now.
