### ISSUE TITLE
Rename "Extended" series

### ISSUE THREAD

**Issue by dreamingfifi** [kriskowal/tengwarjs#33]
To avoid having to decide whether the extended series are from tyeller 1, 2, 3, or 4, a common usage among fans that I quite like is to call them as such:

thuletinco, formenparma, harmacalma, hwestaquesse, antoando, ampaumbar, ancaanga, unqueungwe

**Comment by kriskowal** [comment]
This would be a good introductory project and does not require programming expertise. It amounts to a global search and replace and verification that the tests still pass.

**Comment by dreamingfifi** [comment]
how would I do that? where is this global search?

**Comment by kriskowal** [comment]
Oh, alas, you’re right. You might not need a programmer, but you would need a text editor like VSCode that knows how to communicate with Git.
