### ISSUE TITLE
Need Dan Smith binding for Sindarin Y, diaeresis

### ISSUE THREAD

**Issue by kriskowal** [kriskowal/tengwarjs#34]
Per #28, you mentioned there were three Y tehtar. It seems I overlooked the Sindarin variant and only had the Quenya.

This one is not particularly well documented. Do you happen to have the reference documents for the fonts?

**Comment by dreamingfifi** [comment]
Sure! We have one example, the word "mhellyn" in the third draft of the King's Letter in Sauron Defeated.

**Comment by dreamingfifi** [comment]
oh! You were referring to a different type of reference...
[tengwar annatar.pdf](https://github.com/kriskowal/tengwarjs/files/3722576/tengwar.annatar.pdf)
[Tengwar Formal Keymapping.pdf](https://github.com/kriskowal/tengwarjs/files/3722578/Tengwar.Formal.Keymapping.pdf)

**Comment by kriskowal** [comment]
Thanks. I’ve used this info to support this variant in #35.
